# Generated by Django 3.1.7 on 2021-02-20 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personnel_id', models.PositiveIntegerField(unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=8, unique=True)),
                ('rfid_no', models.CharField(max_length=100, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin.person')),
                ('v_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], default='Enter', max_length=10)),
                ('vehicle', models.ForeignKey(default=datetime.datetime(2021, 2, 20, 16, 29, 24, 533424), on_delete=django.db.models.deletion.PROTECT, to='checkin.vehicle')),
            ],
        ),
    ]
