# Generated by Django 3.1.6 on 2021-02-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('personnel_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=8)),
                ('rfid_no', models.PositiveBigIntegerField(unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin_api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_datetime', models.DateTimeField()),
                ('out_datetime', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkin_api.vehicle')),
            ],
        ),
    ]
