# Generated by Django 3.1.6 on 2021-02-16 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0002_auto_20210216_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='enter',
        ),
        migrations.AddField(
            model_name='log',
            name='direction',
            field=models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], default='Enter', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='vehicle',
            field=models.ForeignKey(default=datetime.datetime(2021, 2, 16, 13, 1, 42, 988683), on_delete=django.db.models.deletion.PROTECT, to='checkin_api.vehicle'),
        ),
    ]
