# Generated by Django 3.1.6 on 2021-02-16 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_api', '0003_auto_20210216_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='vehicle',
            field=models.ForeignKey(default=datetime.datetime(2021, 2, 16, 15, 5, 26, 620731), on_delete=django.db.models.deletion.PROTECT, to='checkin_api.vehicle'),
        ),
    ]
